on:
  repository_dispatch:
    types:
      - publish_spec
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or tag to publish (e.g. refs/heads/development/v2).
        required: true
        default: refs/heads/master
      aliases:
        description: Space-delimited aliases to publish (e.g. latest v2-latest).
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.ref || github.event.inputs.ref }}
        fetch-depth: 0 # Because we will be pushing the gh-pages branch
    - name: Install pre-requisites
      run: pip install -r requirements.txt
    - name: Install mike
      run: pip install mike==1.1.2
    - name: Extract branch or tag name
      id: extract-branch-or-tag-name
      run: echo "::set-output name=ref_name::${REF##*/}"
      env:
        REF: ${{ github.event.client_payload.ref || github.event.inputs.ref }}
    - name: Set Git identity
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Build docs
      run: mike deploy ${{ steps.extract-branch-or-tag-name.outputs.ref_name }} ${{ github.event.inputs.aliases }}
